-- GENERATED by scripts/permissions-sql.mjs from src/domain/permissions.js — do not edit by hand (npm run check-domain fails on drift).
-- The permission matrix, probed through RLS: each read capability as each actor (seeded fake sign-ins, JWT aal claim set).
-- 16 read capabilities × 7 actors; the command rows are checked in tests/admin-domain.test.mjs.
begin;
create extension if not exists pgtap with schema extensions;
select plan(112);

-- fixture (fake, rolled back): the parent who has not accepted the privacy notice, an enrolled principal, rows the seed lacks
insert into auth.users (instance_id, id, aud, role, email, encrypted_password, created_at, updated_at)
values ('00000000-0000-0000-0000-000000000000', '00000000-0000-4000-8000-0000000000c4', 'authenticated', 'authenticated', 'grd03-matrix@example.com', '', now(), now());
insert into public.app_users (user_id, role, guardian_id, status) values ('00000000-0000-4000-8000-0000000000c4', 'parent', 'grd-03', 'active');
insert into public.two_step_enrolled (user_id) values ('00000000-0000-4000-8000-000000000001') on conflict do nothing;
insert into public.student_health (student_id, notes) values ('stu-04', 'Fake matrix note: no nuts.') on conflict (student_id) do update set notes = excluded.notes;
insert into public.sign_in_events (user_id, aal) values ('00000000-0000-4000-8000-000000000006', 'aal1');
insert into public.data_requests (id, doc) values ('drq-matrix-1', '{"id":"drq-matrix-1","guardianId":"grd-01","kind":"export","details":"","status":"open","filedAt":"2026-10-01T05:00:00.000Z","filedBy":"grd-01"}'::jsonb);
insert into public.data_requests (id, doc) values ('drq-matrix-2', '{"id":"drq-matrix-2","guardianId":"grd-02","kind":"correction","details":"Fake: phone number changed.","status":"open","filedAt":"2026-10-01T05:00:00.000Z","filedBy":"grd-02"}'::jsonb);

-- principal_aal2
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal2"}', true);
select is((select count(*) from public.students) > 0, true, 'children_records / principal_aal2');
select is((select count(*) from public.student_health) > 0, true, 'health_notes / principal_aal2');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, true, 'guardian_contacts / principal_aal2');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, true, 'staff_phones / principal_aal2');
select is((select count(*) from public.invoices) > 0, true, 'fees / principal_aal2');
select is((select count(*) from public.attendance) > 0, true, 'attendance / principal_aal2');
select is((select count(*) from public.observations where shared_at is null) > 0, true, 'observations_unshared / principal_aal2');
select is((select count(*) from public.observations where shared_at is not null) > 0, true, 'observations_shared / principal_aal2');
select is((select count(*) from public.progress_events) > 0, true, 'progress / principal_aal2');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, true, 'consents_all / principal_aal2');
select is((select count(*) from public.audit_log) > 0, true, 'audit_log / principal_aal2');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, true, 'account_audit / principal_aal2');
select is((select count(*) from public.sign_in_events) > 0, true, 'sign_in_activity / principal_aal2');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, true, 'data_requests_all / principal_aal2');
select is((select count(*) from public.presentations) > 0, true, 'curriculum / principal_aal2');
select is((select count(*) from public.trip_positions) > 0, true, 'bus_positions / principal_aal2');
reset role;

-- principal_aal1_enrolled
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-000000000001","role":"authenticated","aal":"aal1"}', true);
select is((select count(*) from public.students) > 0, false, 'children_records / principal_aal1_enrolled');
select is((select count(*) from public.student_health) > 0, false, 'health_notes / principal_aal1_enrolled');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'guardian_contacts / principal_aal1_enrolled');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, false, 'staff_phones / principal_aal1_enrolled');
select is((select count(*) from public.invoices) > 0, false, 'fees / principal_aal1_enrolled');
select is((select count(*) from public.attendance) > 0, false, 'attendance / principal_aal1_enrolled');
select is((select count(*) from public.observations where shared_at is null) > 0, false, 'observations_unshared / principal_aal1_enrolled');
select is((select count(*) from public.observations where shared_at is not null) > 0, false, 'observations_shared / principal_aal1_enrolled');
select is((select count(*) from public.progress_events) > 0, false, 'progress / principal_aal1_enrolled');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'consents_all / principal_aal1_enrolled');
select is((select count(*) from public.audit_log) > 0, false, 'audit_log / principal_aal1_enrolled');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, false, 'account_audit / principal_aal1_enrolled');
select is((select count(*) from public.sign_in_events) > 0, false, 'sign_in_activity / principal_aal1_enrolled');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'data_requests_all / principal_aal1_enrolled');
select is((select count(*) from public.presentations) > 0, false, 'curriculum / principal_aal1_enrolled');
select is((select count(*) from public.trip_positions) > 0, false, 'bus_positions / principal_aal1_enrolled');
reset role;

-- teacher
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-000000000002","role":"authenticated","aal":"aal1"}', true);
select is((select count(*) from public.students) > 0, true, 'children_records / teacher');
select is((select count(*) from public.student_health) > 0, true, 'health_notes / teacher');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, true, 'guardian_contacts / teacher');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, false, 'staff_phones / teacher');
select is((select count(*) from public.invoices) > 0, false, 'fees / teacher');
select is((select count(*) from public.attendance) > 0, true, 'attendance / teacher');
select is((select count(*) from public.observations where shared_at is null) > 0, true, 'observations_unshared / teacher');
select is((select count(*) from public.observations where shared_at is not null) > 0, true, 'observations_shared / teacher');
select is((select count(*) from public.progress_events) > 0, true, 'progress / teacher');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'consents_all / teacher');
select is((select count(*) from public.audit_log) > 0, false, 'audit_log / teacher');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, false, 'account_audit / teacher');
select is((select count(*) from public.sign_in_events) > 0, false, 'sign_in_activity / teacher');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'data_requests_all / teacher');
select is((select count(*) from public.presentations) > 0, true, 'curriculum / teacher');
select is((select count(*) from public.trip_positions) > 0, false, 'bus_positions / teacher');
reset role;

-- accountant
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-000000000003","role":"authenticated","aal":"aal1"}', true);
select is((select count(*) from public.students) > 0, true, 'children_records / accountant');
select is((select count(*) from public.student_health) > 0, false, 'health_notes / accountant');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, true, 'guardian_contacts / accountant');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, false, 'staff_phones / accountant');
select is((select count(*) from public.invoices) > 0, true, 'fees / accountant');
select is((select count(*) from public.attendance) > 0, false, 'attendance / accountant');
select is((select count(*) from public.observations where shared_at is null) > 0, false, 'observations_unshared / accountant');
select is((select count(*) from public.observations where shared_at is not null) > 0, false, 'observations_shared / accountant');
select is((select count(*) from public.progress_events) > 0, false, 'progress / accountant');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'consents_all / accountant');
select is((select count(*) from public.audit_log) > 0, true, 'audit_log / accountant');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, false, 'account_audit / accountant');
select is((select count(*) from public.sign_in_events) > 0, false, 'sign_in_activity / accountant');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'data_requests_all / accountant');
select is((select count(*) from public.presentations) > 0, false, 'curriculum / accountant');
select is((select count(*) from public.trip_positions) > 0, true, 'bus_positions / accountant');
reset role;

-- driver
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-000000000004","role":"authenticated","aal":"aal1"}', true);
select is((select count(*) from public.students) > 0, true, 'children_records / driver');
select is((select count(*) from public.student_health) > 0, false, 'health_notes / driver');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'guardian_contacts / driver');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, false, 'staff_phones / driver');
select is((select count(*) from public.invoices) > 0, false, 'fees / driver');
select is((select count(*) from public.attendance) > 0, false, 'attendance / driver');
select is((select count(*) from public.observations where shared_at is null) > 0, false, 'observations_unshared / driver');
select is((select count(*) from public.observations where shared_at is not null) > 0, false, 'observations_shared / driver');
select is((select count(*) from public.progress_events) > 0, false, 'progress / driver');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'consents_all / driver');
select is((select count(*) from public.audit_log) > 0, false, 'audit_log / driver');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, false, 'account_audit / driver');
select is((select count(*) from public.sign_in_events) > 0, false, 'sign_in_activity / driver');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'data_requests_all / driver');
select is((select count(*) from public.presentations) > 0, false, 'curriculum / driver');
select is((select count(*) from public.trip_positions) > 0, true, 'bus_positions / driver');
reset role;

-- parent_consented
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-000000000006","role":"authenticated","aal":"aal1"}', true);
select is((select count(*) from public.students) > 0, true, 'children_records / parent_consented');
select is((select count(*) from public.student_health) > 0, true, 'health_notes / parent_consented');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'guardian_contacts / parent_consented');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, false, 'staff_phones / parent_consented');
select is((select count(*) from public.invoices) > 0, true, 'fees / parent_consented');
select is((select count(*) from public.attendance) > 0, true, 'attendance / parent_consented');
select is((select count(*) from public.observations where shared_at is null) > 0, false, 'observations_unshared / parent_consented');
select is((select count(*) from public.observations where shared_at is not null) > 0, true, 'observations_shared / parent_consented');
select is((select count(*) from public.progress_events) > 0, false, 'progress / parent_consented');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'consents_all / parent_consented');
select is((select count(*) from public.audit_log) > 0, false, 'audit_log / parent_consented');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, false, 'account_audit / parent_consented');
select is((select count(*) from public.sign_in_events) > 0, false, 'sign_in_activity / parent_consented');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'data_requests_all / parent_consented');
select is((select count(*) from public.presentations) > 0, false, 'curriculum / parent_consented');
select is((select count(*) from public.trip_positions) > 0, true, 'bus_positions / parent_consented');
reset role;

-- parent_no_consent
select set_config('role', 'authenticated', true), set_config('request.jwt.claims', '{"sub":"00000000-0000-4000-8000-0000000000c4","role":"authenticated","aal":"aal1"}', true);
select is((select count(*) from public.students) > 0, false, 'children_records / parent_no_consent');
select is((select count(*) from public.student_health) > 0, false, 'health_notes / parent_no_consent');
select is((select count(*) from public.guardians where id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'guardian_contacts / parent_no_consent');
select is((select count(*) from public.staff_contacts where staff_id <> coalesce(app.my_staff_id(), '') and phone is not null) > 0, false, 'staff_phones / parent_no_consent');
select is((select count(*) from public.invoices) > 0, false, 'fees / parent_no_consent');
select is((select count(*) from public.attendance) > 0, false, 'attendance / parent_no_consent');
select is((select count(*) from public.observations where shared_at is null) > 0, false, 'observations_unshared / parent_no_consent');
select is((select count(*) from public.observations where shared_at is not null) > 0, false, 'observations_shared / parent_no_consent');
select is((select count(*) from public.progress_events) > 0, false, 'progress / parent_no_consent');
select is((select count(*) from public.consents where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'consents_all / parent_no_consent');
select is((select count(*) from public.audit_log) > 0, false, 'audit_log / parent_no_consent');
select is((select count(*) from public.audit_log where entity = 'appUser') > 0, false, 'account_audit / parent_no_consent');
select is((select count(*) from public.sign_in_events) > 0, false, 'sign_in_activity / parent_no_consent');
select is((select count(*) from public.data_requests where guardian_id <> coalesce(app.my_guardian_id(), '')) > 0, false, 'data_requests_all / parent_no_consent');
select is((select count(*) from public.presentations) > 0, false, 'curriculum / parent_no_consent');
select is((select count(*) from public.trip_positions) > 0, false, 'bus_positions / parent_no_consent');
reset role;

select * from finish();
rollback;
