// Starter list of Montessori presentations for ages about 2 to 6, in the five areas of the classroom.
// Generic, traditional material and presentation names only (no brand, school or person). The school should edit it:
// order, ages and wording differ between training traditions. Ages are in months and are a typical guide, not a rule.
// Loading is idempotent: the command matches on `key` (curriculumKey), so a second load adds nothing.
// Each row is [name, ageFromMonths, ageToMonths, one-line description].

import { curriculumKey } from './curriculum.js';

const PRACTICAL_LIFE = [
  ['Carrying a mat and rolling it up', 24, 48, 'Unrolling, working on and rolling up a floor mat.'],
  ['Carrying a tray', 24, 42, 'Carrying a tray with both hands without spilling.'],
  ['Carrying a chair', 24, 42, 'Lifting and placing a chair quietly.'],
  ['Walking on the line', 30, 54, 'Walking heel to toe along a line, then with an object.'],
  ['Opening and closing a door quietly', 24, 42, 'Using the handle and closing without a sound.'],
  ['Opening and closing bottles and jars', 24, 48, 'Twisting lids on and off.'],
  ['Pouring dry materials between jugs', 24, 42, 'Pouring beans or rice from one jug to another.'],
  ['Pouring water between jugs', 30, 48, 'Pouring water with control, wiping any drops.'],
  ['Spooning beans', 24, 42, 'Transferring beans with a spoon between bowls.'],
  ['Transferring with tongs', 30, 54, 'Moving objects between bowls with tongs.'],
  ['Transferring with tweezers', 36, 60, 'Fine pincer practice with tweezers.'],
  ['Transferring with a sponge', 30, 54, 'Squeezing water from one bowl to another.'],
  ['Transferring with a dropper', 36, 60, 'Drawing up and releasing water with a dropper.'],
  ['Folding a cloth', 30, 54, 'Folding a square cloth in half and in quarters.'],
  ['Folding a napkin', 36, 60, 'Folding napkins for the table.'],
  ['Dressing frame: large buttons', 30, 54, 'Fastening and unfastening large buttons.'],
  ['Dressing frame: small buttons', 36, 60, 'Fastening and unfastening small buttons.'],
  ['Dressing frame: zip', 30, 54, 'Opening and closing a zip.'],
  ['Dressing frame: snaps', 30, 54, 'Pressing snap fasteners together and apart.'],
  ['Dressing frame: buckles', 36, 60, 'Fastening and unfastening a buckle.'],
  ['Dressing frame: bow tying', 42, 72, 'Tying a bow with two laces.'],
  ['Lacing', 36, 60, 'Threading a lace through a lacing card or frame.'],
  ['Braiding', 42, 72, 'Braiding three strands of ribbon or wool.'],
  ['Hand washing', 24, 48, 'The full sequence of washing and drying hands.'],
  ['Table washing', 30, 60, 'Scrubbing and drying a table in an ordered sequence.'],
  ['Dish washing', 36, 66, 'Washing, rinsing and drying a plate or cup.'],
  ['Polishing a wooden or metal object', 36, 66, 'Applying polish and buffing to a shine.'],
  ['Flower arranging', 30, 60, 'Cutting stems and arranging flowers in a small vase.'],
  ['Watering a plant', 24, 54, 'Using a small watering can with care.'],
  ['Sweeping with a broom and dustpan', 30, 60, 'Sweeping a spill into a dustpan.'],
  ['Setting a table', 36, 66, 'Laying a mat, plate, cup and cutlery.'],
  ['Slicing a banana', 30, 54, 'Cutting a banana with a child-safe knife.'],
  ['Peeling a carrot', 36, 66, 'Using a peeler safely on a carrot.'],
  ['Spreading with a knife', 30, 54, 'Spreading butter or paste on bread.'],
  ['Sewing: running stitch', 48, 72, 'A simple running stitch on a sewing card or cloth.'],
  ['Grace and courtesy: greeting someone', 24, 54, 'Looking at a person and saying hello.'],
  ['Grace and courtesy: interrupting politely', 30, 60, 'Waiting, then saying excuse me.'],
  ['Grace and courtesy: offering help', 36, 66, 'Asking whether a friend would like help.'],
];

const SENSORIAL = [
  ['Knobbed cylinders: block 1', 30, 54, 'Matching cylinders that vary in diameter and height.'],
  ['Knobbed cylinders: block 2', 30, 54, 'Matching cylinders that vary in diameter and height.'],
  ['Knobbed cylinders: block 3', 30, 54, 'Matching cylinders that vary in diameter and height.'],
  ['Knobbed cylinders: block 4', 30, 54, 'Matching cylinders that vary in diameter and height.'],
  ['Knobless cylinders', 42, 66, 'Grading coloured cylinders by size.'],
  ['Pink tower', 30, 60, 'Ten cubes built in order of size.'],
  ['Brown stair', 30, 60, 'Ten prisms graded in thickness.'],
  ['Red rods', 30, 60, 'Ten rods graded in length.'],
  ['Colour tablets: box 1', 30, 48, 'Matching three pairs of primary colours.'],
  ['Colour tablets: box 2', 36, 54, 'Matching eleven pairs of colours.'],
  ['Colour tablets: box 3', 42, 66, 'Grading seven shades of nine colours.'],
  ['Geometric cabinet', 36, 66, 'Matching plane shapes to their frames.'],
  ['Geometric solids', 36, 66, 'Naming and feeling three-dimensional shapes.'],
  ['Superimposed geometric figures', 48, 72, 'Building shapes in a graded sequence.'],
  ['Constructive triangles: triangular box', 42, 72, 'Making shapes from triangles.'],
  ['Constructive triangles: rectangular box', 48, 72, 'Making parallelograms and rectangles from triangles.'],
  ['Constructive triangles: large hexagonal box', 48, 72, 'Making larger shapes from triangles.'],
  ['Binomial cube', 42, 72, 'Assembling a cube from eight blocks by pattern.'],
  ['Trinomial cube', 48, 72, 'Assembling a cube from twenty-seven blocks by pattern.'],
  ['Sound cylinders', 36, 66, 'Matching and grading sounds.'],
  ['Montessori bells', 42, 72, 'Matching and grading musical notes.'],
  ['Thermic tablets', 36, 66, 'Matching pairs by temperature.'],
  ['Thermic bottles', 36, 66, 'Matching bottles of warm and cool water.'],
  ['Baric tablets', 36, 66, 'Grading wooden tablets by weight.'],
  ['Rough and smooth boards', 24, 48, 'Feeling and naming rough and smooth.'],
  ['Touch tablets', 30, 54, 'Matching surfaces by touch, blindfolded.'],
  ['Fabric matching', 30, 54, 'Matching pairs of fabrics by touch.'],
  ['Mystery bag', 36, 66, 'Identifying objects by touch alone.'],
  ['Smelling bottles', 36, 66, 'Matching pairs of scents.'],
  ['Tasting bottles', 36, 66, 'Matching and naming sweet, sour, salty and bitter.'],
  ['Sorting by size and shape', 24, 48, 'Sorting everyday objects by size and shape.'],
  ['Geometric stick material', 54, 72, 'Exploring lines and angles with sticks.'],
];

const LANGUAGE = [
  ['Classified objects: vocabulary baskets', 24, 48, 'Naming real objects grouped by theme.'],
  ['Three-part cards: nomenclature', 30, 66, 'Matching pictures, labels and control cards.'],
  ['Sound games: beginning sounds', 36, 60, 'Hearing the first sound of a word.'],
  ['Sound games: ending sounds', 42, 66, 'Hearing the last sound of a word.'],
  ['Sound games: middle sounds', 48, 72, 'Hearing the middle sound of a word.'],
  ['Rhymes and poems', 24, 72, 'Reciting short rhymes and poems.'],
  ['Storytelling and retelling', 30, 72, 'Listening to a story and retelling it in order.'],
  ['Sandpaper letters: group 1', 36, 60, 'Tracing and sounding the first group of letters.'],
  ['Sandpaper letters: group 2', 36, 60, 'Tracing and sounding the second group of letters.'],
  ['Sandpaper letters: group 3', 36, 66, 'Tracing and sounding the third group of letters.'],
  ['Sandpaper letters: group 4', 42, 66, 'Tracing and sounding the fourth group of letters.'],
  ['Sandpaper letters: group 5', 42, 66, 'Tracing and sounding the fifth group of letters.'],
  ['Sandpaper letters: phonograms', 48, 72, 'Tracing and sounding letter pairs such as sh and ch.'],
  ['Sand tray writing', 36, 60, 'Writing letters in a tray of fine sand.'],
  ['Metal insets: tracing', 36, 66, 'Tracing a shape and filling it with lines.'],
  ['Metal insets: designs', 42, 72, 'Combining shapes into patterns.'],
  ['Chalkboard writing', 42, 66, 'Writing letters large on a chalkboard.'],
  ['Handwriting on lined paper', 54, 72, 'Writing words and sentences on lines.'],
  ['Moveable alphabet: three-letter words', 42, 66, 'Building simple phonetic words.'],
  ['Moveable alphabet: longer phonetic words', 48, 72, 'Building words of four or more sounds.'],
  ['Moveable alphabet: phrases and sentences', 54, 72, 'Composing short sentences.'],
  ['Object boxes: first reading', 42, 66, 'Reading three-letter words and matching objects.'],
  ['Pink series: word cards', 48, 72, 'Reading phonetic three-letter word cards.'],
  ['Blue series: word cards', 54, 72, 'Reading words with blends.'],
  ['Green series: phonogram cards', 54, 72, 'Reading words with phonograms.'],
  ['Puzzle words', 54, 72, 'Learning common words that break the rules.'],
  ['Command cards: action reading', 48, 72, 'Reading an instruction and carrying it out.'],
  ['Grammar: introduction to the noun', 54, 72, 'Finding and marking naming words.'],
  ['Grammar: introduction to the verb', 54, 72, 'Finding and marking action words.'],
  ['Grammar: introduction to the adjective', 54, 72, 'Finding and marking describing words.'],
  ['Reading comprehension: matching sentences to pictures', 54, 72, 'Reading a sentence and choosing its picture.'],
];

const MATH = [
  ['Number rods', 36, 60, 'Counting rods from one to ten.'],
  ['Sandpaper numerals', 36, 60, 'Tracing and naming the numerals 0 to 9.'],
  ['Number rods with numerals', 42, 66, 'Placing numeral cards beside the rods.'],
  ['Spindle boxes', 42, 66, 'Counting loose spindles into the compartments 0 to 9.'],
  ['Cards and counters', 42, 66, 'Placing counters beneath numeral cards.'],
  ['Memory game of numbers', 48, 66, 'Fetching a number card and counting the objects.'],
  ['Short bead stair', 36, 66, 'Counting the coloured bead bars from one to nine.'],
  ['Golden beads: introduction to the decimal system', 48, 72, 'Units, tens, hundreds and thousands in beads.'],
  ['Golden beads: number cards', 48, 72, 'Matching quantities to numeral cards.'],
  ['Golden beads: addition', 54, 72, 'Adding with the bead material.'],
  ['Golden beads: subtraction', 54, 72, 'Subtracting with the bead material.'],
  ['Golden beads: multiplication', 60, 72, 'Multiplying with the bead material.'],
  ['Golden beads: division', 60, 72, 'Dividing with the bead material.'],
  ['Teen boards', 48, 72, 'Building the numbers 11 to 19.'],
  ['Ten boards', 48, 72, 'Building the numbers 10 to 99.'],
  ['Hundred board', 48, 72, 'Placing tiles to build the numbers 1 to 100.'],
  ['Linear counting: short chains', 54, 72, 'Counting and labelling squares and cubes.'],
  ['Linear counting: long chains', 60, 72, 'Skip counting with the long bead chains.'],
  ['Stamp game: addition', 54, 72, 'Adding with tiles for units, tens and hundreds.'],
  ['Stamp game: subtraction', 54, 72, 'Subtracting with the stamp tiles.'],
  ['Addition strip board', 54, 72, 'Finding sums with the strips.'],
  ['Subtraction strip board', 54, 72, 'Finding differences with the strips.'],
  ['Addition snake game', 54, 72, 'Building a snake of bead bars to add.'],
  ['Small bead frame', 60, 72, 'Reading and writing large numbers on the frame.'],
  ['Fraction circles', 54, 72, 'Exploring halves, thirds and quarters.'],
  ['Odd and even with counters', 48, 66, 'Pairing counters to see odd and even.'],
  ['Counting objects one to one', 30, 54, 'Touching and counting small objects one by one.'],
  ['Sorting and patterns', 30, 54, 'Sorting objects and continuing a pattern.'],
];

const CULTURE = [
  ['Land and water globe', 30, 60, 'Feeling the rough land and smooth water on a globe.'],
  ['Continent globe', 36, 66, 'Naming the continents by their colours.'],
  ['Puzzle map of the world', 36, 66, 'Placing and naming the continents.'],
  ['Puzzle map of Asia', 48, 72, 'Placing and naming the countries of Asia.'],
  ['Puzzle map of India', 48, 72, 'Placing and naming the states of India.'],
  ['Land and water forms', 42, 72, 'Island, lake, peninsula and gulf in trays.'],
  ['Flags of the world', 48, 72, 'Matching and naming flags.'],
  ['Living and non-living', 30, 54, 'Sorting objects into living and non-living.'],
  ['Plant and animal', 30, 54, 'Sorting pictures of plants and animals.'],
  ['Parts of a plant', 36, 66, 'Naming root, stem, leaf and flower.'],
  ['Parts of a leaf', 42, 66, 'Naming the parts of a leaf.'],
  ['Botany cabinet: leaf shapes', 42, 72, 'Matching leaf shapes in the cabinet.'],
  ['Parts of a flower', 48, 72, 'Naming the parts of a flower.'],
  ['Parts of an animal', 42, 72, 'Naming the body parts of an animal.'],
  ['Vertebrates and invertebrates', 48, 72, 'Sorting animals by whether they have a backbone.'],
  ['Life cycle of a butterfly', 42, 72, 'Egg, caterpillar, pupa and butterfly.'],
  ['Life cycle of a frog', 42, 72, 'Egg, tadpole and frog.'],
  ['Planting seeds', 30, 66, 'Planting and caring for a seed.'],
  ['Needs of living things', 36, 66, 'Water, air, light and food.'],
  ['Habitats of animals', 42, 72, 'Matching animals to where they live.'],
  ['Days of the week', 36, 66, 'Naming and ordering the days.'],
  ['Months of the year', 42, 72, 'Naming and ordering the months.'],
  ['The seasons', 42, 72, 'Describing the seasons and the weather.'],
  ['Telling the time: the clock', 54, 72, 'Reading the hours on a clock face.'],
  ['My family tree', 42, 72, 'Placing the people in a family in order.'],
  ['Sink and float', 36, 66, 'Testing objects in water.'],
  ['Magnetic and non-magnetic', 42, 72, 'Testing objects with a magnet.'],
  ['Colour mixing', 36, 66, 'Mixing the primary colours.'],
  ['The solar system: sun, earth and moon', 54, 72, 'An introduction to day, night and the moon.'],
  ['Art: drawing and painting', 24, 72, 'Free drawing and painting with varied tools.'],
  ['Art: collage and clay', 30, 72, 'Cutting, sticking and modelling.'],
  ['Music: singing and rhythm', 24, 72, 'Songs, clapping and rhythm instruments.'],
];

const AREAS = [
  ['practicalLife', PRACTICAL_LIFE],
  ['sensorial', SENSORIAL],
  ['language', LANGUAGE],
  ['math', MATH],
  ['culture', CULTURE],
];

/** @returns {Omit<import('../store/schema.js').Presentation,'id'>[]} the starter list, without ids (the command assigns them). */
export function starterPresentations() {
  const out = [];
  for (const [area, rows] of AREAS) {
    rows.forEach(([name, ageFromMonths, ageToMonths, description], i) => {
      out.push({ key: curriculumKey(area, name), area, name, sequence: (i + 1) * 10, ageFromMonths, ageToMonths, description, active: true, source: 'starter' });
    });
  }
  return out;
}
