#!/usr/bin/env node
// First-run setup of a NEW (empty) project: school profile, academic years, programs, fee heads, staff
// (at least the principal, with the email they will sign in with) and optionally bus routes — written through
// the same public.persist() the app uses, validated by the same domain checks first.
//
//   cp supabase/first-run.example.json first-run.json      # first-run.json is gitignored: it holds real details
//   (edit first-run.json)
//   node scripts/first-run-sql.mjs first-run.json > first-run.sql
//   → Supabase dashboard → SQL Editor → paste first-run.sql → Run. Then the principal signs in with that email.
//
// Safe to paste only once: persist() is guarded by the 'first-run' revision, so a second run fails with CONFLICT
// and changes nothing. Fee structures, students and guardians are added in the app afterwards (or by CSV import).
// Output goes to stdout only; this script never writes real details into the repository.

import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { createEmptyDb } from '../src/store/schema.js';
import { validateDb } from '../src/domain/validate.js';
import { appendAudit } from '../src/domain/audit.js';

export const DEFAULT_FEE_HEADS = [
  { id: 'fh-tuition', name: 'Tuition fee', kind: 'tuition' },
  { id: 'fh-materials', name: 'Materials fee', kind: 'materials' },
  { id: 'fh-transport', name: 'Transport fee', kind: 'transport' },
  { id: 'fh-admission', name: 'Admission fee', kind: 'admission' },
  { id: 'fh-latefee', name: 'Late fee', kind: 'lateFee' },
];

const sq = s => `'${String(s).replace(/'/g, "''")}'`;

export function firstRunSql(cfg, now = new Date()) {
  const db = createEmptyDb();
  const fail = m => { throw new Error(`first-run config: ${m}`); };
  if (!cfg || typeof cfg !== 'object') fail('not a JSON object');
  if (!cfg.school || !cfg.school.name) fail('school.name is required');
  db.school = { ...db.school, ...cfg.school, currentAcademicYearId: cfg.currentAcademicYearId || null };
  db.academicYears = (cfg.academicYears || []).map(a => ({ id: a.id, label: a.label || a.id, startDate: a.startDate, endDate: a.endDate }));
  db.programs = (cfg.programs || []).map(p => ({ id: p.id, name: p.name, ageRange: p.ageRange || '', teacherIds: [] }));
  db.feeHeads = (cfg.feeHeads || DEFAULT_FEE_HEADS).map(h => ({ ...h }));
  db.staff = (cfg.staff || []).map(s => ({ id: s.id, firstName: s.firstName, lastName: s.lastName || '', role: s.role, programIds: [...(s.programIds || [])], phone: s.phone || '', email: String(s.email || '').trim().toLowerCase() || null }));
  for (const s of db.staff) for (const pid of s.programIds) { const p = db.programs.find(x => x.id === pid); if (p) p.teacherIds.push(s.id); }
  db.routes = (cfg.routes || []).map(r => ({ id: r.id, name: r.name, busNo: r.busNo || '', driverId: r.driverId, attendantId: r.attendantId || null, transportFeePaise: r.transportFeePaise,
    stops: (r.stops || []).map((st, i) => ({ id: st.id || `${r.id}-stop-${i + 1}`, name: st.name, lat: st.lat, lng: st.lng, seq: st.seq ?? i + 1, scheduledPickup: st.scheduledPickup || '', scheduledDrop: st.scheduledDrop || '' })), path: null }));
  const principals = db.staff.filter(s => s.role === 'admin');
  if (!principals.length) fail('at least one staff member with role "admin" (the principal) is required');
  for (const s of db.staff) {
    if (!['admin', 'teacher', 'accountant', 'driver'].includes(s.role)) fail(`staff ${s.id}: unknown role ${s.role}`);
    // every role signs in with an email code (drivers too: there is no other driver sign-in)
    if (!s.email) fail(`staff ${s.id}: an email is required to sign in`);
    if (s.email && !/^[^@\s]+@[^@\s]+\.[^@\s]+$/.test(s.email)) fail(`staff ${s.id}: invalid email`);
  }
  const ctx = { actor: { role: 'system', id: 'first-run' }, now: now.toISOString(), today: now.toISOString().slice(0, 10) };
  appendAudit(db, ctx, { entity: 'school', entityId: 'school', action: 'firstRun', summary: `school set up: ${db.academicYears.length} academic year(s), ${db.programs.length} program(s), ${db.staff.length} staff, ${db.routes.length} route(s)` });
  const errors = validateDb(db).filter(v => v.severity !== 'warning');
  if (errors.length) fail(`not valid:\n  ${errors.map(e => `${e.code} ${e.entity} ${e.id}: ${e.message}`).join('\n  ')}`);
  const changes = { school: db.school, upserts: { academicYears: db.academicYears, programs: db.programs, feeHeads: db.feeHeads, staff: db.staff, routes: db.routes }, counters: db.counters, audit: db.auditLog };
  const json = JSON.stringify(changes);
  if (json.includes('$first$')) fail('text contains the dollar-quote tag');
  const emails = db.staff.map(p => p.email).filter(Boolean);
  return `-- First-run setup (generated by scripts/first-run-sql.mjs). Paste into the Supabase SQL Editor once.
-- A second run fails with CONFLICT (revision 'first-run') and changes nothing.
select public.persist('first-run', 0, $first$${json}$first$::jsonb);

-- Staff who already signed in before this ran are linked now (later sign-ins are linked by the auth trigger).
-- Same rule as the trigger: only a confirmed mailbox, and never an account created with a password.
insert into public.app_users (user_id, role, staff_id, status)
select u.id, s.role, s.id, 'active'
from auth.users u join public.staff_contacts c on lower(c.email) = lower(u.email) join public.staff s on s.id = c.staff_id
where lower(u.email) in (${emails.map(sq).join(', ')})
  and u.email_confirmed_at is not null and coalesce(u.encrypted_password, '') = ''
on conflict (user_id) do nothing;
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const file = process.argv[2];
  if (!file) { console.error('usage: node scripts/first-run-sql.mjs first-run.json > first-run.sql'); process.exit(2); }
  try {
    process.stdout.write(firstRunSql(JSON.parse(readFileSync(file, 'utf8'))));
  } catch (e) {
    console.error(e.message);
    process.exit(1);
  }
}
