#!/usr/bin/env node
// Generate supabase/tests/permissions.test.sql from the permission matrix (src/domain/permissions.js): one pgTAP
// assertion per read capability and actor, run as the seeded sign-in with the JWT `aal` claim set exactly as PostgREST
// would, so RLS itself answers each cell. Fixture rows (FIXTURE) are added inside the test's transaction.
//   node scripts/permissions-sql.mjs           → writes the file
//   node scripts/permissions-sql.mjs --check   → exit 1 if the file is missing or out of date (part of npm run check-domain)

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { PERMISSIONS, MATRIX_ACTORS, FIXTURE } from '../src/domain/permissions.js';

const root = join(dirname(fileURLToPath(import.meta.url)), '..');
const target = join(root, 'supabase/tests/permissions.test.sql');
const q = s => `'${String(s).replace(/'/g, "''")}'`;

export function buildPermissionsSql() {
  const reads = PERMISSIONS.capabilities.filter(c => c.sql);
  const actors = PERMISSIONS.actors.map(a => a.key);
  const lines = [];
  lines.push('-- GENERATED by scripts/permissions-sql.mjs from src/domain/permissions.js — do not edit by hand (npm run check-domain fails on drift).');
  lines.push('-- The permission matrix, probed through RLS: each read capability as each actor (seeded fake sign-ins, JWT aal claim set).');
  lines.push(`-- ${reads.length} read capabilities × ${actors.length} actors; the command rows are checked in tests/admin-domain.test.mjs.`);
  lines.push('begin;');
  lines.push('create extension if not exists pgtap with schema extensions;');
  lines.push(`select plan(${reads.length * actors.length});`);
  lines.push('');
  lines.push('-- fixture (fake, rolled back): the parent who has not accepted the privacy notice, an enrolled principal, rows the seed lacks');
  const nc = MATRIX_ACTORS.parent_no_consent;
  lines.push(`insert into auth.users (instance_id, id, aud, role, email, encrypted_password, created_at, updated_at)
values ('00000000-0000-0000-0000-000000000000', ${q(nc.userId)}, 'authenticated', 'authenticated', ${q(nc.email)}, '', now(), now());`);
  lines.push(`insert into public.app_users (user_id, role, guardian_id, status) values (${q(nc.userId)}, 'parent', ${q(nc.link.guardianId)}, 'active');`);
  const enrolled = [...new Set(Object.values(MATRIX_ACTORS).filter(a => a.enrolled).map(a => a.userId))];
  for (const u of enrolled) lines.push(`insert into public.two_step_enrolled (user_id) values (${q(u)}) on conflict do nothing;`);
  for (const [sid, notes] of Object.entries(FIXTURE.healthNotes)) {
    lines.push(`insert into public.student_health (student_id, notes) values (${q(sid)}, ${q(notes)}) on conflict (student_id) do update set notes = excluded.notes;`);
  }
  for (const e of FIXTURE.signInEvents) lines.push(`insert into public.sign_in_events (user_id, aal) values (${q(e.userId)}, ${q(e.aal)});`);
  for (const r of FIXTURE.dataRequests) {
    lines.push(`insert into public.data_requests (id, doc) values (${q(r.id)}, ${q(JSON.stringify({ ...r, filedAt: '2026-10-01T05:00:00.000Z', filedBy: r.guardianId }))}::jsonb);`);
  }
  for (const a of actors) {
    const x = MATRIX_ACTORS[a];
    lines.push('');
    lines.push(`-- ${a}`);
    lines.push(`select set_config('role', 'authenticated', true), set_config('request.jwt.claims', ${q(JSON.stringify({ sub: x.userId, role: 'authenticated', aal: x.aal }))}, true);`);
    for (const c of reads) {
      lines.push(`select is((${c.sql}) > 0, ${c.allow[a]}, ${q(`${c.key} / ${a}`)});`);
    }
    lines.push('reset role;');
  }
  lines.push('');
  lines.push('select * from finish();');
  lines.push('rollback;');
  return `${lines.join('\n')}\n`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) {
  const sql = buildPermissionsSql();
  if (process.argv.includes('--check')) {
    const now = existsSync(target) ? readFileSync(target, 'utf8') : null;
    if (now !== sql) { console.log('permissions-sql --check FAIL: supabase/tests/permissions.test.sql is out of date. Run: node scripts/permissions-sql.mjs'); process.exit(1); }
    console.log('permissions-sql --check OK');
  } else {
    writeFileSync(target, sql);
    console.log(`supabase/tests/permissions.test.sql written (${PERMISSIONS.capabilities.filter(c => c.sql).length} read capabilities × ${PERMISSIONS.actors.length} actors)`);
  }
}
